tasks:
  - init: |
      pip install jupyterlab rise
      jupyter-nbextension install rise --py --sys-prefix
      jupyter-nbextension enable rise --py --sys-prefix

vscode:
  extensions:
    - ms-python.python
